import { QueryProvider, ThemeProvider } from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HydratedData } from "@/components/hydrated-data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = async ({ children }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<QueryProvider>
					<HydratedData>
						<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
							{children}
						</ThemeProvider>
					</HydratedData>
				</QueryProvider>
			</body>
		</html>
	);
};

export default RootLayout;
